### ISSUE TITLE
About mouse button and key codes

### ISSUE THREAD

**Issue by nkatte** [tsoding/vitanim#1]
The source code of [sdl for nim](https://github.com/nim-lang/sdl2) declares some constants that i think you should use on your code, for example, the mouse left button are declared [here](https://github.com/nim-lang/sdl2/blob/f1f2d147bc32dee2111696483812337e7ec15ed6/src/sdl2.nim#L1741) as BUTTON_LEFT and de scan code for _f_ should be [SDL_SCANCODE_F](https://github.com/nim-lang/sdl2/blob/f1f2d147bc32dee2111696483812337e7ec15ed6/src/sdl2/private/keycodes.nim#L7).
I don't know if this is the correct way of handling the buttons and keys, i am not a nim programmer.
I hope this helps you.

**Comment by rexim** [comment]
@nkatte oh, that is cool! Thank you so much! Feel free to submit a Pull Request. :)

**Comment by rexim** [comment]
Invalidated by #2. We don't use https://github.com/nim-lang/sdl2 anymore.
